### ISSUE TITLE
microsoft.internal.helix.admin.commandline and microsoft.internal.dnceng.commandline.secret new versions not working

### ISSUE THREAD

**Issue by dkurepa** [dotnet/dnceng#1068]
The newer versions of the tools above are not working. All commands are failling with
```
Unhandled exception. System.ArgumentException: There was an error parsing the Connection String: Input cannot be empty.
 ---> System.ArgumentException: Input cannot be empty.
   at Microsoft.ApplicationInsights.Extensibility.Implementation.ConfigString.ConfigStringParser.Parse(String configString)
   at Microsoft.ApplicationInsights.Extensibility.Implementation.Endpoints.EndpointProvider.ParseConnectionString(String connectionString)
   --- End of inner exception stack trace ---
   at Microsoft.ApplicationInsights.Extensibility.Implementation.Endpoints.EndpointProvider.ParseConnectionString(String connectionString)
   at Microsoft.ApplicationInsights.Extensibility.Implementation.Endpoints.EndpointProvider.set_ConnectionString(String value)
   at Microsoft.ApplicationInsights.Extensibility.TelemetryConfiguration.set_ConnectionString(String value)
   at Microsoft.DncEng.CommandLineLib.DependencyInjectedConsoleApp.<>c__DisplayClass2_0.<ConfigureDefaultServices>b__2(TelemetryConfiguration c)
   at Microsoft.Extensions.Options.ConfigureNamedOptions`1.Configure(String name, TOptions options)
   at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
   at Microsoft.Extensions.Options.UnnamedOptionsManager`1.get_Value()
   at Microsoft.Extensions.Logging.ApplicationInsights.ApplicationInsightsLoggerProvider..ctor(IOptions`1 telemetryConfigurationOptions, IOptions`1 applicationInsightsLoggerOptions)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitIEnumerable(IEnumerableCallSite enumerableCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type serviceType)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.DncEng.CommandLineLib.DependencyInjectedConsoleApp.RunCommandAsync(IServiceProvider provider, IEnumerable`1 args)
   at Microsoft.DncEng.CommandLineLib.DependencyInjectedConsoleApp.RunAsync(IEnumerable`1 args)
   at Microsoft.DncEng.CommandLineLib.DependencyInjectedConsoleApp.RunAsync(IEnumerable`1 args)
   at Microsoft.Internal.DncEng.CommandLine.Secret.Program.<Main>(String[] args)
```
I think this probably started happening after moving to Application Insights Connection Strings over Instrumentation Keys [here](https://dev.azure.com/dnceng/internal/_git/dotnet-helix-service/commit/cdd2ed98c19d58b728ffe8590856fc614e622ced?refName=refs/heads/main&path=/src/ServiceFabric/AutoScaler/AutoScaleActorService/Program.cs&_a=contents&tab=details), I think

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [x] Internal Infrastructure Improvements
### Release Note Description
Fix App Insights connection string references for Helix admin CLIs

**Comment by dougbu** [comment]
b/c `4.1.156-prerelease-2023091506` predates the merge of commit [cdd2ed98c19d58b728ffe8590856fc614e622ced](https://dev.azure.com/dnceng/internal/_git/dotnet-helix-service/commit/cdd2ed98c19d58b728ffe8590856fc614e622ced) and fails in exactly the same way, I suggest the problem was introduced in `helix-admin` and `secret` a bit earlier.

`v4.1.155` seems to work

**Comment by garath** [comment]
PR: [!35898](https://dev.azure.com/dnceng/internal/_git/dotnet-helix-service/pullrequest/35898)
