### ISSUE TITLE
Helix agents are unable to upload the results to Azdo

### ISSUE THREAD

**Issue by pavelsavara** [dotnet/dnceng#167]
```
helix.test_reporting.azure_devops_result_publisher.TerminalError: TF400813: The user 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa' is not authorized to access this resource.

Traceback (most recent call last):

  File "/etc/helix/scripts/helix/test_reporting/azure_devops_result_publisher.py", line 271, in _send

    return execute()

  File "/etc/helix/scripts/helix/test_reporting/azure_devops_result_publisher.py", line 333, in <lambda>
    self._azdo_parameters.test_run_id

  File "/etc/helix/scripts/azure/devops/v5_1/test/test_client.py", line 679, in add_test_results_to_test_run

    content=content)

  File "/etc/helix/scripts/helix/test_reporting/azure_devops_result_publisher.py", line 70, in _hook_send

    return old_send(*args, **kwargs)

  File "/etc/helix/scripts/azure/devops/client.py", line 104, in _send

    response = self._send_request(request=request, headers=headers, content=content, media_type=media_type)

  File "/etc/helix/scripts/azure/devops/client.py", line 68, in _send_request

    self._handle_error(request, response)

  File "/etc/helix/scripts/azure/devops/client.py", line 247, in _handle_error

    raise AzureDevOpsServiceError(wrapped_exception)

azure.devops.exceptions.AzureDevOpsServiceError: TF400813: The user 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa' is not authorized to access this resource.
```

happens on multiple PRs, example https://github.com/dotnet/runtime/pull/86759/checks?check_run_id=14087737047

Perhaps wasm is running on some machine pool which didn't receive the access tokens when it was rotated ?

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description

**Comment by oleksandr-didyk** [comment]
Transferred to a known issue -> https://github.com/dotnet/arcade/issues/13778
