### ISSUE TITLE
Correct `dotnet-helix-machines-image-generation` pipeline

### ISSUE THREAD

**Issue by dougbu** [dotnet/dnceng#2406]
The [dotnet-helix-machines NuGet.config](https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines?path=/NuGet.config) file now references the `dotnet-eng-internal` feed. We therefore need to run `NuGetAuthenticate@1` before any build step that may attempt to restore packages. This is currently breaking at least the [dotnet-helix-machines-image-generation](https://dev.azure.com/dnceng/internal/_build?definitionId=1037) pipeline. Need to fix that pipeline.

Sample error:
``` text
D:\a\_work\1\s\Directory.Build.props(9,3): error : Could not resolve SDK "Microsoft.DotNet.Arcade.Sdk". Exactly one of the probing messages below indicates why we could not resolve the SDK. Investigate and resolve that message to correctly specify the SDK.
D:\a\_work\1\s\Directory.Build.props(9,3): error :   SDK resolver "Microsoft.DotNet.MSBuildWorkloadSdkResolver" returned null.
D:\a\_work\1\s\Directory.Build.props(9,3): error :   System.AggregateException: One or more errors occurred. (Unable to load the service index for source https://dnceng.pkgs.visualstudio.com/internal/_packaging/dotnet-eng-internal/nuget/v3/index.json.)
D:\a\_work\1\s\Directory.Build.props(9,3): error :  ---> NuGet.Protocol.Core.Types.FatalProtocolException: Unable to load the service index for source https://dnceng.pkgs.visualstudio.com/internal/_packaging/dotnet-eng-internal/nuget/v3/index.json.
D:\a\_work\1\s\Directory.Build.props(9,3): error :  ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 401 (Unauthorized).
D:\a\_work\1\s\Directory.Build.props(9,3): error :    at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
D:\a\_work\1\s\Directory.Build.props(9,3): error :    at NuGet.Protocol.HttpSource.<>c__DisplayClass15_0`1.<<GetAsync>b__0>d.MoveNext()
D:\a\_work\1\s\Directory.Build.props(9,3): error : --- End of stack trace from previous location ---
```

I kicked off [#2024033001](https://dev.azure.com/dnceng/internal/_build/results?buildId=2418722&view=results) in [dotnet-helix-machines-weekly](https://dev.azure.com/dnceng/internal/_build?definitionId=959) and confirmed it can run now, downloading all programs from [dotnet-helix-machines-ci](https://dev.azure.com/dnceng/internal/_build?definitionId=596). Other helix-machines pipelines have run with the latest commits from 'main' without issue.

### Release Note Category

- [ ] Feature changes/additions
- [ ] Bug fixes
- [x] Internal Infrastructure Improvements

### Release Note Description

Updated the [dotnet-helix-machines-image-generation](https://dev.azure.com/dnceng/internal/_build?definitionId=1037) pipeline in reaction to the #2396 fix. Those changes broke `dotnet restore` in the [dotnet-helix-machines](https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines) without NuGet authentication.

**Comment by dougbu** [comment]
fixed in [!38621](https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/pullrequest/38621)

**Comment by dougbu** [comment]
done
