### ISSUE TITLE
[rollout issue] Secret-manager scenario tests failing in production

### ISSUE THREAD

**Issue by riarenas** [dotnet/dnceng#312]
https://dnceng.visualstudio.com/internal/_build/results?buildId=2211162&view=results failed during the secret-manager scenario tests with errors of the form: 

```
##[error]Unhandled Exception: AzureServiceTokenProviderCredential unable to authenticate
```

```
Microsoft.DncEng.CommandLineLib.FailWithExitCodeException : Exception of type 'Microsoft.DncEng.CommandLineLib.FailWithExitCodeException' was thrown.
  Stack Trace:
     at Microsoft.DncEng.SecretManager.Commands.SynchronizeCommand.RunAsync(CancellationToken cancellationToken) in /_/src/SecretManager/Microsoft.DncEng.SecretManager/Commands/SynchronizeCommand.cs:line 231
   at Microsoft.DncEng.SecretManager.Tests.ScenarioTestsBase.ExecuteSynchronizeCommand(String manifest) in /_/src/SecretManager/Microsoft.DncEng.SecretManager.ScenarioTests/ScenarioTestsBase.cs:line 55
   at Microsoft.DncEng.SecretManager.Tests.ServiceBusTests.RotateConnectionStringSecretTest() in /_/src/SecretManager/Microsoft.DncEng.SecretManager.ScenarioTests/ServiceBusTests.cs:line 68
   at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
   at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
   at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
   at NUnit.Framework.Internal.Execution.SimpleWorkItem.<>c__DisplayClass4_0.<PerformWork>b__0()
   at NUnit.Framework.Internal.ContextUtils.<>c__DisplayClass1_0`1.<DoIsolated>b__0(Object _)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at NUnit.Framework.Internal.ContextUtils.DoIsolated(ContextCallback callback, Object state)
   at NUnit.Framework.Internal.ContextUtils.DoIsolated[T](Func`1 func)
   at NUnit.Framework.Internal.Execution.SimpleWorkItem.PerformWork()
```

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description

**Comment by riarenas** [comment]
I think I found it: https://github.com/dotnet/dnceng/blob/main/eng/deploy.yaml#L248 references a different variable group and secret from the one I cycled this morning, but they need to match. I'll update the existing secret and retry.

**Comment by riarenas** [comment]
I created a new secret to be used specifically for the scenario tests and added it to engkeyvault. We should consider adding this secret to secret-manager.

**Comment by riarenas** [comment]
We use a different AAD registered application for the scenario tests. However, that application is currently orphaned with no owners: https://ms.portal.azure.com/#view/Microsoft_AAD_RegisteredApps/ApplicationMenuBlade/~/Owners/appId/06d0d96d-9d42-402d-9d48-98821e74eb50 so I'm unable to generate a new secret for it.

I think the options here are:
* figure out if we can quickly gain ownership over the application (no idea how, azure support ticket maybe?)
* Create a new application

**Comment by riarenas** [comment]
I created an Azure support request to regain ownership of the application. We'll see how that goes.

**Comment by riarenas** [comment]
Ticket was closed without action because the support engineer contacted me on a day where I wasn't available and they didn't read the ticket description. Reopened the ticket and still waiting for this

**Comment by riarenas** [comment]
After a lot of redirection this is finally fixed.
