### ISSUE TITLE
[android] Networking connection issues for `windows.11.amd64.android.open` queue

### ISSUE THREAD

**Issue by matouskozak** [dotnet/dnceng#3405]
### Build

https://dev.azure.com/dnceng-public/public/_build/results?buildId=735679

### Build leg reported

android_[arm/arm64] Release AllSubset_Mono

### Known issue core information

Fill out the known issue JSON section by following the [step by step documentation on how to create a known issue](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md#how-to-create-a-known-issue-step-by-step)

```json
 {
    "ErrorMessage" : "System.Net.Sockets.SocketException : Network is unreachable",
    "BuildRetry": false,
    "ErrorPattern": "",
    "ExcludeConsoleLog": false
 }
 ```

 @dotnet/dnceng

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Additional information about the issue reported

Android devices from `windows.11.amd64.android.open` queue are having problems connecting the network, causing CI failures on `runtime-extra-platforms` pipeline in the dotnet/runtime repo. The issue was originally reported as runtime issue (https://github.com/dotnet/runtime/issues/104709) but based on further investigation looks like an infrastructure issue.

Stack trace examples from `System.Net.Sockets.Tests` on different builds:
```07-10 02:54:56.978 12860 18040 I DOTNET  : 1) 	[FAIL] System.Net.Sockets.Tests.SendTo_ArraySync.Datagram_UDP_ShouldImplicitlyBindLocalEndpoint   Test name: System.Net.Sockets.Tests.SendTo_ArraySync.Datagram_UDP_ShouldImplicitlyBindLocalEndpoint
07-10 02:54:56.978 12860 18040 I DOTNET  :    Assembly:  [System.Net.Sockets.Tests, Version=9.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51]
07-10 02:54:56.978 12860 18040 I DOTNET  :    Exception messages: System.Net.Sockets.SocketException : Network is unreachable   Exception stack traces:    at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, Boolean disconnectOnFailure, String callerName)
07-10 02:54:56.978 12860 18040 I DOTNET  :    at System.Net.Sockets.Socket.SendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint remoteEP)
07-10 02:54:56.978 12860 18040 I DOTNET  :    at System.Net.Sockets.Tests.SocketHelperArraySync.<>c__DisplayClass11_0.<SendToAsync>b__0() in /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/SocketTestHelper.cs:line 92
07-10 02:54:56.978 12860 18040 I DOTNET  :    at System.Threading.Tasks.Task`1[[System.Int32, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].InnerInvoke()
07-10 02:54:56.978 12860 18040 I DOTNET  :    at System.Threading.Tasks.Task.<>c.<.cctor>b__292_0(Object obj)
07-10 02:54:56.978 12860 18040 I DOTNET  :    at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
07-10 02:54:56.978 12860 18040 I DOTNET  : --- End of stack trace from previous location ---
07-10 02:54:56.978 12860 18040 I DOTNET  :    at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
07-10 02:54:56.978 12860 18040 I DOTNET  :    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
07-10 02:54:56.978 12860 18040 I DOTNET  : --- End of stack trace from previous location ---
07-10 02:54:56.978 12860 18040 I DOTNET  :    at System.Net.Sockets.Tests.SendTo`1.<Datagram_UDP_ShouldImplicitlyBindLocalEndpoint>d__7[[System.Net.Sockets.Tests.SocketHelperArraySync, System.Net.Sockets.Tests, Version=9.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51]].MoveNext() in /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/SendTo.cs:line 90
07-10 02:54:56.978 12860 18040 I DOTNET  : --- End of stack trace from previous location ---
07-10 02:54:56.978 12860 18040 I DOTNET  :    Execution time: 0.031889
07-10 02:54:56.978 12860 18040 I DOTNET  : 2) 	[FAIL] System.Net.Sockets.Tests.SendTo_ArraySync.Datagram_UDP_AccessDenied_Throws_DoesNotBind   Test name: System.Net.Sockets.Tests.SendTo_ArraySync.Datagram_UDP_AccessDenied_Throws_DoesNotBind
07-10 02:54:56.978 12860 18040 I DOTNET  :    Assembly:  [System.Net.Sockets.Tests, Version=9.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51]
07-10 02:54:56.978 12860 18040 I DOTNET  :    Exception messages: Assert.Equal() Failure: Values differ
07-10 02:54:56.978 12860 18040 I DOTNET  : Expected: AccessDenied
07-10 02:54:56.978 12860 18040 I DOTNET  : Actual:   NetworkUnreachable   Exception stack traces:    at System.Net.Sockets.Tests.SendTo`1.<Datagram_UDP_AccessDenied_Throws_DoesNotBind>d__8[[System.Net.Sockets.Tests.SocketHelperArraySync, System.Net.Sockets.Tests, Version=9.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51]].MoveNext() in /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/SendTo.cs:line 105
07-10 02:54:56.978 12860 18040 I DOTNET  : --- End of stack trace from previous location ---
07-10 02:54:56.978 12860 18040 I DOTNET  :    Execution time: 0.0532853
```

```
07-11 14:56:41.123  4473  8928 I DOTNET  : 	[FAIL] System.Net.Sockets.Tests.UdpClientTest.Connect_StringHost_Success
07-11 14:56:41.123  4473  8928 I DOTNET  : System.Net.Sockets.SocketException : Network is unreachable 114.114.114.114:53
07-11 14:56:41.123  4473  8928 I DOTNET  :    at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
07-11 14:56:41.123  4473  8928 I DOTNET  :    at System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
07-11 14:56:41.123  4473  8928 I DOTNET  :    at System.Net.Sockets.Socket.Connect(IPAddress address, Int32 port)
07-11 14:56:41.123  4473  8928 I DOTNET  :    at System.Net.Sockets.Socket.Connect(String host, Int32 port)
07-11 14:56:41.123  4473  8928 I DOTNET  :    at System.Net.Sockets.Tests.UdpClientTest.Connect_StringHost_Success() in /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/UdpClientTest.cs:line 466
07-11 14:56:41.123  4473  8928 I DOTNET  :    at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Method(Object obj, IntPtr* args)
07-11 14:56:41.123  4473  8928 I DOTNET  :    at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=735679
**Error message validated:** `[System.Net.Sockets.SocketException : Network is unreachable`]
**Result validation:** :x: Known issue did not match with the provided build.
**Validation performed at:** 7/12/2024 8:32:13 AM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[745393](https://dev.azure.com/dnceng-public/public/_build/results?buildId=745393)|dotnet/runtime|[System.Net.Sockets.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=745393&view=ms.vss-test-web.build-test-results-tab&runId=18835576&resultId=177014)||
|[743450](https://dev.azure.com/dnceng-public/public/_build/results?buildId=743450)|dotnet/runtime|[System.Net.Sockets.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=743450&view=ms.vss-test-web.build-test-results-tab&runId=18782032&resultId=171178)||
|[743391](https://dev.azure.com/dnceng-public/public/_build/results?buildId=743391)|dotnet/runtime|[System.Net.Sockets.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=743391&view=ms.vss-test-web.build-test-results-tab&runId=18780258&resultId=164958)||
|[743077](https://dev.azure.com/dnceng-public/public/_build/results?buildId=743077)|dotnet/runtime|[System.Net.Sockets.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=743077&view=ms.vss-test-web.build-test-results-tab&runId=18767900&resultId=170181)||
|[742744](https://dev.azure.com/dnceng-public/public/_build/results?buildId=742744)|dotnet/runtime|[System.Net.Sockets.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=742744&view=ms.vss-test-web.build-test-results-tab&runId=18759928&resultId=167992)||
|[742370](https://dev.azure.com/dnceng-public/public/_build/results?buildId=742370)|dotnet/runtime|[System.Net.Sockets.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=742370&view=ms.vss-test-web.build-test-results-tab&runId=18746046&resultId=178084)||
|[742110](https://dev.azure.com/dnceng-public/public/_build/results?buildId=742110)|dotnet/runtime|[System.Net.Sockets.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=742110&view=ms.vss-test-web.build-test-results-tab&runId=18736922&resultId=174647)||
|[741767](https://dev.azure.com/dnceng-public/public/_build/results?buildId=741767)|dotnet/runtime|[System.Net.Sockets.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=741767&view=ms.vss-test-web.build-test-results-tab&runId=18737018&resultId=170820)||
|[740838](https://dev.azure.com/dnceng-public/public/_build/results?buildId=740838)|dotnet/runtime|[System.Net.Sockets.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=740838&view=ms.vss-test-web.build-test-results-tab&runId=18699226&resultId=177055)|dotnet/runtime#104541|
|[739967](https://dev.azure.com/dnceng-public/public/_build/results?buildId=739967)|dotnet/runtime|[System.Net.Sockets.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=739967&view=ms.vss-test-web.build-test-results-tab&runId=18675402&resultId=175821)||
|[739577](https://dev.azure.com/dnceng-public/public/_build/results?buildId=739577)|dotnet/runtime|[System.Net.Sockets.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=739577&view=ms.vss-test-web.build-test-results-tab&runId=18666998&resultId=171100)||
|[739539](https://dev.azure.com/dnceng-public/public/_build/results?buildId=739539)|dotnet/runtime|[System.Net.Sockets.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=739539&view=ms.vss-test-web.build-test-results-tab&runId=18666538&resultId=175520)||
|[739937](https://dev.azure.com/dnceng-public/public/_build/results?buildId=739937)|dotnet/runtime|[System.Net.Sockets.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=739937&view=ms.vss-test-web.build-test-results-tab&runId=18666542&resultId=179341)||
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|3|13|

**Comment by matouskozak** [comment]
The internet connection to the devices was restored. Closing.
