### ISSUE TITLE
OutOfMemoryException MemoryStreamTests.MemoryStream_SeekOverflow_Throws

### ISSUE THREAD

**Issue by steveharter** [dotnet/dnceng#610]
### Build

https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=382187

Tests are using\manipulating a 2GB buffer - not sure if infra issue or not.
```
[06:25:42.9703650] 2023-08-22 03:25:43.059 System.IO.Tests[29757:35945170] 	[PASS] System.IO.Tests.MemoryStreamTests.MemoryStream_SeekOverflow_Throws
[06:25:42.9779930] 2023-08-22 03:25:43.067 System.IO.Tests[29757:35945170]    Test name: System.IO.Tests.MemoryStreamTests.MemoryStream_SeekOverflow_Throws(mode: Position, bufferSize: 2147483591, origin: 0)
[06:25:42.9780420] 2023-08-22 03:25:43.067 System.IO.Tests[29757:35945170]    Test case: System.IO.Tests.MemoryStreamTests.MemoryStream_SeekOverflow_Throws
[06:25:42.9790880] 2023-08-22 03:25:43.068 System.IO.Tests[29757:35945170]    Exception messages: System.OutOfMemoryException : Insufficient memory to continue the execution of the program.
[06:25:42.9804190] 2023-08-22 03:25:43.070 System.IO.Tests[29757:35945170]    Exception stack traces:    at System.IO.Tests.MemoryStreamTests.MemoryStream_SeekOverflow_Throws(SeekMode mode, Int32 bufferSize, Int32 origin)
[06:25:42.9804520]    at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Method(Object obj, IntPtr* args)
[06:25:42.9805040] 2023-08-22 03:25:43.070 System.IO.Tests[29757:35945170]    at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
[06:25:42.9806220] 2023-08-22 03:25:43.070 System.IO.Tests[29757:35945170]    Execution time: 0.0027594
[06:25:42.9808750] 2023-08-22 03:25:43.070 System.IO.Tests[29757:35945170] 	[FAIL] System.IO.Tests.MemoryStreamTests.MemoryStream_SeekOverflow_Throws
[06:25:42.9812490] 2023-08-22 03:25:43.071 System.IO.Tests[29757:35945170] 	[FAIL] System.IO.Tests.MemoryStreamTests.MemoryStream_SeekOverflow_Throws   Test name: System.IO.Tests.MemoryStreamTests.MemoryStream_SeekOverflow_Throws(mode: Position, bufferSize: 2147483591, origin: 0)   Test case: System.IO.Tests.MemoryStreamTests.MemoryStream_SeekOverflow_Throws
[06:25:42.9812650]    Assembly:  [System.IO.Tests, Version=8.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51]
[06:25:42.9812770] 2023-08-22 03:25:43.071 System.IO.Tests[29757:35945170]    Exception messages: System.OutOfMemoryException : Insufficient memory to continue the execution of the program.   Exception stack traces:    at System.IO.Tests.MemoryStreamTests.MemoryStream_SeekOverflow_Throws(SeekMode mode, Int32 bufferSize, Int32 origin)
[06:25:42.9812890]    at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Method(Object obj, IntPtr* args)
[06:25:42.9821860] 2023-08-22 03:25:43.072 System.IO.Tests[29757:35945170]    at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
[06:25:42.9822170]    Execution time: 0.0027594
[06:25:42.9884610] 2023-08-22 03:25:43.078 System.IO.Tests[29757:35945170]    Test name: System.IO.Tests.MemoryStreamTests.MemoryStream_SeekOverflow_Throws(mode: Position, bufferSize: 2147483591, origin: 2147483591)
[06:25:42.9884940] 2023-08-22 03:25:43.078 System.IO.Tests[29757:35945170]    Test case: System.IO.Tests.MemoryStreamTests.MemoryStream_SeekOverflow_Throws
[06:25:42.9903650] 2023-08-22 03:25:43.079 System.IO.Tests[29757:35945170]    Exception messages: System.OutOfMemoryException : Insufficient memory to continue the execution of the program.
[06:25:42.9904520] 2023-08-22 03:25:43.079 System.IO.Tests[29757:35945170]    Exception stack traces:    at System.IO.Tests.MemoryStreamTests.MemoryStream_SeekOverflow_Throws(SeekMode mode, Int32 bufferSize, Int32 origin)
[06:25:42.9904700]    at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Method(Object obj, IntPtr* args)
[06:25:42.9905290] 2023-08-22 03:25:43.080 System.IO.Tests[29757:35945170]    at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
[06:25:42.9905950] 2023-08-22 03:25:43.080 System.IO.Tests[29757:35945170]    Execution time: 0.0017628
[06:25:42.9906660] 2023-08-22 03:25:43.080 System.IO.Tests[29757:35945170] 	[FAIL] System.IO.Tests.MemoryStreamTests.MemoryStream_SeekOverflow_Throws
[06:25:42.9907490] 2023-08-22 03:25:43.080 System.IO.Tests[29757:35945170] 	[FAIL] System.IO.Tests.MemoryStreamTests.MemoryStream_SeekOverflow_Throws   Test name: System.IO.Tests.MemoryStreamTests.MemoryStream_SeekOverflow_Throws(mode: Position, bufferSize: 2147483591, origin: 2147483591)   Test case: System.IO.Tests.MemoryStreamTests.MemoryStream_SeekOverflow_Throws
[06:25:42.9907590]    Assembly:  [System.IO.Tests, Version=8.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51]
[06:25:42.9907670] 2023-08-22 03:25:43.080 System.IO.Tests[29757:35945170]    Exception messages: System.OutOfMemoryException : Insufficient memory to continue the execution of the program.   Exception stack traces:    at System.IO.Tests.MemoryStreamTests.MemoryStream_SeekOverflow_Throws(SeekMode mode, Int32 bufferSize, Int32 origin)
[06:25:42.9907720]    at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Method(Object obj, IntPtr* args)
[06:25:42.9912370] 2023-08-22 03:25:43.081 System.IO.Tests[29757:35945170]    at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
[06:25:42.9912530]    Execution time: 0.0017628
```

### Build leg reported

System.Runtime.Tests.WorkItemExecution

### Pull Request

https://github.com/dotnet/runtime/pull/90796

### Known issue core information

```json
 {
    "ErrorMessage" : "Exception stack traces:    at System.IO.Tests.MemoryStreamTests.MemoryStream_SeekOverflow_Throws",
    "BuildRetry": false
 }
 ```

 @dotnet/dnceng

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=382187
**Error message validated:** `Exception stack traces:    at System.IO.Tests.MemoryStreamTests.MemoryStream_SeekOverflow_Throws`
**Result validation: :x:** Known issue did not match with the provided build.
**Validation performed at:** 8/22/2023 8:48:24 PM UTC

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=382187
**Error message validated:** `Exception stack traces:    at System.IO.Tests.MemoryStreamTests.MemoryStream_SeekOverflow_Throws`
**Result validation: :x:** Known issue did not match with the provided build.
**Validation performed at:** 8/22/2023 8:48:24 PM UTC

**Comment by riarenas** [comment]
The error message was not matched with the provided build, so this known issue is not getting any hits. I'm going to close this for now, but feel free to reopen and fix the error message.
