### ISSUE TITLE
pylint failing helix-machines validation

### ISSUE THREAD

**Issue by garath** [dotnet/dnceng#942]
The validation done using `pylint` as part of image creation is failing. 

First glance is that the command parameters have changed in recent update, meaning we need to update the validation scripts to match (and that there isn't any actual linting problem)

```
2023-10-02 18:29:11Z pr-windows.10.amd64-baseimages-update: Traceback (most recent call last):
2023-10-02 18:29:11Z pr-windows.10.amd64-baseimages-update:   File "C:\h\w\A3610919\w\A7810956\u\validate.py", line 214, in <module>
2023-10-02 18:29:11Z pr-windows.10.amd64-baseimages-update:     if not run_pylint():
2023-10-02 18:29:11Z pr-windows.10.amd64-baseimages-update:   File "C:\h\w\A3610919\w\A7810956\u\validate.py", line 173, in run_pylint
2023-10-02 18:29:11Z pr-windows.10.amd64-baseimages-update:     pylint_results = Run(['--errors-only', '--disable=no-member', script_dir], do_exit=False)
2023-10-02 18:29:11Z pr-windows.10.amd64-baseimages-update: TypeError: Run.__init__() got an unexpected keyword argument 'do_exit'
2023-10-02 18:29:11Z pr-windows.10.amd64-baseimages-update: ['Test' END OF WORK ITEM LOG: Command exited with 1]
```

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description

**Comment by garath** [comment]
PR [!34184](https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/pullrequest/34184).

Draft for now while the validation pipeline runs for testing. If that succeeds, I'll publish.
